"""add dialogs and messages tables

Revision ID: b7cfa1f0d945
Revises: 839d668a20bd
Create Date: 2025-11-21 19:04:26.977745

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "b7cfa1f0d945"
down_revision: Union[str, Sequence[str], None] = "839d668a20bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dialogs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dialogs_is_active"), "dialogs", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_dialogs_user_id"), "dialogs", ["user_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dialog_id", sa.Integer(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dialog_id"],
            ["dialogs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_dialog_id"), "messages", ["dialog_id"], unique=False
    )
    op.create_index(op.f("ix_messages_role"), "messages", ["role"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_role"), table_name="messages")
    op.drop_index(op.f("ix_messages_dialog_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_dialogs_user_id"), table_name="dialogs")
    op.drop_index(op.f("ix_dialogs_is_active"), table_name="dialogs")
    op.drop_table("dialogs")
    # ### end Alembic commands ###
