from typing import Optional, Protocol

from app.domain.models.dialog import DialogEntity


class DialogRepository(Protocol):
    def create(self, dialog: DialogEntity) -> DialogEntity: ...
    def get_by_id(self, dialog_id: int) -> Optional[DialogEntity]: ...
    def get_active_by_user_id(self, user_id: int) -> Optional[DialogEntity]: ...
    def update(self, dialog: DialogEntity) -> DialogEntity: ...
    def deactivate_user_dialogs(self, user_id: int) -> None: ...
